// ── App Config ────────────────────────────────────────────────────────────────
const CONFIG = {
  API_BASE: 'http://localhost:3001/api',
  DEBOUNCE_DELAY: 300,
  MAX_RECENT_SEARCHES: 6,
  MAX_SAVED_JOBS: 50,
  CACHE_TTL: 5 * 60 * 1000,
};

// ── Search Suggestions (prefix → expansions) ──────────────────────────────────
// Keys should be SHORT (2-4 chars) so partial typing triggers them
const SEARCH_SUGGESTIONS = {
  'so':  ['Software Engineer', 'Software Developer'],
  'sw':  ['Software Engineer', 'Software Developer'],
  'se':  ['Senior Software Engineer', 'Senior Developer', 'Security Engineer'],
  'fr':  ['Frontend Developer', 'Frontend Engineer', 'Fresher Software Developer'],
  'ba':  ['Backend Developer', 'Backend Engineer', 'Bangalore Jobs'],
  'fu':  ['Full Stack Developer', 'Full Stack Engineer'],
  'fs':  ['Full Stack Developer', 'Full Stack Engineer'],
  'da':  ['Data Scientist', 'Data Engineer', 'Data Analyst'],
  'ds':  ['Data Scientist', 'Data Science Intern'],
  'de':  ['DevOps Engineer', 'Data Engineer', 'Delhi Jobs'],
  'ml':  ['Machine Learning Engineer', 'ML Engineer'],
  'ai':  ['AI Engineer', 'AI Researcher'],
  'ui':  ['UI Designer', 'UI/UX Designer'],
  'ux':  ['UX Designer', 'UX Researcher'],
  'pr':  ['Product Manager', 'Product Designer', 'Product Analyst'],
  'pm':  ['Product Manager', 'Project Manager'],
  'mo':  ['Mobile Developer', 'Mobile Engineer'],
  'an':  ['Android Developer', 'Android Engineer', 'Analytics Engineer'],
  'io':  ['iOS Developer', 'iOS Engineer'],
  'cy':  ['Cybersecurity Engineer', 'Cyber Security Analyst'],
  'cl':  ['Cloud Engineer', 'Cloud Architect'],
  'qa':  ['QA Engineer', 'Quality Assurance Engineer'],
  'hr':  ['HR Manager', 'HR Executive', 'Human Resources'],
  'ma':  ['Marketing Manager', 'Marketing Analyst', 'Machine Learning'],
  'sa':  ['Sales Manager', 'Sales Engineer', 'Salesforce Developer'],
  'in':  ['Internship', 'Infrastructure Engineer'],
  'py':  ['Python Developer', 'Python Engineer'],
  'ja':  ['Java Developer', 'Java Engineer', 'JavaScript Developer'],
  'no':  ['Node.js Developer', 'Node.js Engineer'],
  're':  ['React Developer', 'React Native Developer', 'Remote Jobs'],
  'go':  ['Golang Developer', 'Go Engineer'],
  'ru':  ['Ruby on Rails Developer'],
  'sc':  ['Scrum Master', 'Scala Developer'],
  'te':  ['Tech Lead', 'Technical Writer', 'Test Engineer'],
  'fi':  ['Finance Manager', 'Financial Analyst'],
  'op':  ['Operations Manager', 'Operations Analyst'],
  'bu':  ['Business Analyst', 'Business Development'],
  'co':  ['Content Writer', 'Content Manager', 'Community Manager'],
  'gr':  ['Graphic Designer', 'Growth Hacker', 'Growth Manager'],
  'em':  ['Embedded Engineer', 'Email Marketing'],
  'bl':  ['Blockchain Developer', 'Blockchain Engineer'],
  'dj':  ['Django Developer'],
  'sp':  ['Spring Boot Developer', 'SaaS Product Manager'],
  'ku':  ['Kubernetes Engineer'],
  'do':  ['Docker Engineer', 'DevOps Engineer'],
  'aw':  ['AWS Engineer', 'AWS Solutions Architect'],
  'az':  ['Azure Developer', 'Azure Engineer'],
  'gc':  ['GCP Engineer', 'Google Cloud Engineer'],
};

// ── Empty State Suggestions ───────────────────────────────────────────────────
const EMPTY_SUGGESTIONS = [
  { label:'Frontend Developer',   icon:'💻' },
  { label:'Product Manager',      icon:'🎯' },
  { label:'Data Scientist',       icon:'📊' },
  { label:'UX Designer',          icon:'🎨' },
  { label:'Software Engineer',    icon:'⚙️' },
  { label:'Internship',           icon:'🎓' },
];